-- liquibase formatted sql

-- changeset anton:2
create table balance
(
    id              int generated by default as identity,
    red             int,
    green           int,
    blue            int,

    id_drivers      int NULL UNIQUE,

    primary key (id),
    foreign key (id_drivers) references drivers(id)
);

